# Generated by Django 2.1.7 on 2019-10-24 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191012_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
