# Generated by Django 2.1.7 on 2019-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191026_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(0, '----'), (1, '飲み物'), (2, '食べ物'), (3, 'その他')], default=1, verbose_name='種類'),
        ),
    ]
