# Generated by Django 2.1.7 on 2019-10-27 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191028_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default=1, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
