# Generated by Django 2.1.7 on 2019-10-30 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191028_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
